export {default as Home} from './HomePage'
export {default as Contact} from './ContactPage'
export {default as About} from './AboutPage'
export {default as Cart } from './CartPage'
export {default as Reg} from './RegPage.tsx'